### ISSUE TITLE
CSS Opacity and Internet Explorer

### ISSUE THREAD

**Issue by aliebuck** [ded/bonzo#121]
Setting opacity to `0` does not work in IE 8 and older, however `"0"` does work. And setting it to `null` or `""` does not work in IE 9 and older.

Also when setting the opacity through the IE Developer Tools console starts using the `filter` property in IE 9, and doesn't work at all in IE 10.

**Comment by rvagg** [comment]
We probably need to switch this to a check for `!= 'object'`: https://github.com/ded/bonzo/blob/8b616a4ab7df00693629670399585f292b2a087a/src/bonzo.js#L785

and this should probably include a check for `opasity` to include the feature detect instead of just the the `ie` check: https://github.com/ded/bonzo/blob/8b616a4ab7df00693629670399585f292b2a087a/src/bonzo.js#L790

I'll have a go when I find the time unless @jacobbuck you want to submit a pull request for this? Or perhaps @ded (or someone else watching) has time.

**Comment by aliebuck** [comment]
Yep, I just noticed the `ie` check too, also in the same statement `iter.opacity` would return false if equal `0`.
And if the opacity was `null` or `""`, it would still apply the `filter` property with a value of `0`.
