### ISSUE TITLE
Methods depending on insert clone node

### ISSUE THREAD

**Issue by digitarald** [ded/bonzo#13]
`appendTo`, `prependTo`, `insertBefore`, `insertAfter`; all the methods calling `insert` clone the node they move. This caused weird behaviour in my test project, since references suddenly pointed to document-less fragments and not the code I just appended.

Just wanted to verify that this is intended behaviour and why? Maybe I learn something new about what this fixes or why it is good behaviour?

**Comment by ded** [comment]
@digitarald thanks for asking, and it's not a crazy thing to question either. The cloning is indeed intended (jQuery does the same) so that the node can be inserted in multiple places — for what would otherwise just be some node being passed around a bunch of places. Take the following:

``` html
<ul>
  <li>one</li>
  <li>two</li>
  <li>three</li>
</ul>
```

``` js
$('<em>hello </em>').prependTo('li');
```

This creates your original <code>em</code> element and then clones it for each <code>li</code> element found - creating the following output:

``` html
<ul>
  <li><em>hello </em>one</li>
  <li><em>hello </em>two</li>
  <li><em>hello </em>three</li>
</ul>
```
